apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: infrastructure
spec:
  interval: 1m0s
  validation: 'none'
  sourceRef:
    kind: GitRepository
    name: infrastructure
  path: ./infrastructure
  prune: true