name: Deploy a Bicep file to Azure

on:
  pull_request:
    branches: ['main']
   # paths:
   #   - 'cluster/**'

jobs:

  deploy-bicep:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        id-token: write

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID}}
          tenant-id: ${{ secrets.TENANT_ID}}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }}
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./cluster/modules.bicep
          parameters: 
            sourceKind=GitRepository
            environment=Dev
          failOnStdErr: false